quarkus:
  datasource:
    username: postgres
    password: postgres
    db-kind: postgresql
    jdbc:
      max-size: 16
      url: jdbc:postgresql://localhost:5432/postgres
  hibernate-orm:
    database:
      generation: none
application:
  greeting:
    recipient: "LinkedIn Learning Students"
rooms-api/mp-rest/url: http://localhost:8080