quarkus:
  datasource:
    username: postgres
    password: postgres
    db-kind: postgresql
    jdbc:
      max-size: 16
      url: jdbc:postgresql://localhost:5432/some-database
  hibernate-orm:
    database:
      generation: non
application:
  greeting:
    recipient: "LinkedIn Learning Students"
