quarkus:
  swagger-ui:
    enable: true
  datasource:
    username: postgres
    password: postgres
    db-kind: postgresql
    jdbc:
      max-size: 16
      url: jdbc:postgresql://localhost:5432/postgres
  hibernate-orm:
    database:
      generation: update
application:
  greeting:
    recipient: Java devs of the world
rooms-api/mp-rest/url: http://localhost:8080
mp:
  openapi:
    extensions:
      smallrye:
        info:
          title: Postgres Java Playground
          version: 1.0.0
          description: Learning Postgres and Hibernate